runtime: nodejs10

automatic_scaling:
  max_instances: 1

env_variables:
  GOOGLE_CLOUD_PROJECT: bbq-casava-chips
  GCLOUD_STORAGE_BUCKET: test-public

handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301